#!/bin/bash

# This script is used to update the Lineage manifest file

echo "You are going to update the Lineage manifest file."
echo "During the update, the current AOSP work directory (aosptree/) will be updated."
echo "If you have any local changes, they will be lost."
echo "Do you want to continue? [y/N]"
read -r answer
if [[ ! $answer =~ ^[Yy]$ ]]
then
    echo "Aborting"
    exit 1
fi

echo Init repo tree using Lineage OS manifest
pushd ../aosptree
repo init -u https://github.com/LineageOS/android.git -b lineage-18.1 --git-lfs
repo sync build/make
wget -O - https://raw.githubusercontent.com/waydroid/android_vendor_waydroid/lineage-18.1/manifest_scripts/generate-manifest.sh | bash
repo sync -c --force-sync -j4
repo manifest -r -o ../manifests/waydroid-static.xml
popd

# Add the warning line at the beginning of the manifest
sed -i '2i\\n<!-- Autogenerated. Please do not edit. Run update_lineage_manifest.sh to update. -->\n' lineage-static.xml

echo -e "\n\033[32m   Done   \033[0m"
