#!/bin/bash

# This script is used to update the AOSP manifest file

if [ "$1" ]; then
    echo "Using AOSP manifest at $1"
    revision=$1
else
    echo "Using AOSP manifest at refs/tags/android-14.0.0_r25"
    revision=refs/tags/android-14.0.0_r25
fi

echo "You are going to update the AOSP manifest file."
echo "During the update, the current AOSP work directory (aosptree/) will be updated."
echo "If you have any local changes, they will be lost."
echo "Do you want to continue? [y/N]"
read -r answer
if [[ ! $answer =~ ^[Yy]$ ]]
then
    echo "Aborting"
    exit 1
fi

echo Init repo tree using AOSP manifest
mkdir -p ../aospbasetree
pushd ../aospbasetree
repo init -u https://android.googlesource.com/platform/manifest.git -b $revision --git-lfs
repo sync -c --force-sync -j4
repo manifest -r -o ../manifests/aosp-static.xml
popd

# Add the warning line at the beginning of the manifest
sed -i '2i\\n<!-- Autogenerated. Please do not edit. Run update_aosp_manifest.sh to update. -->\n' aosp-static.xml

echo -e "\n\033[32m   Done   \033[0m"
